#!/usr/bin/env node
/**
 * Writes landing/assets/icons.svg: a sprite of the editor's own glyphs, so the
 * landing page draws the same marks the product does.
 *
 *   node landing/tools/build-sprite.mjs
 *   DESIGNLAYER_REPO=../designlayer node tools/build-sprite.mjs   (standalone)
 *
 * Reads src/core/icons.ts through esbuild rather than copying path data by
 * hand, so a redrawn glyph in the editor is one re-run away from the site.
 */

import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { createRequire } from "node:module"

const here = path.dirname(fileURLToPath(import.meta.url))
// The DesignLayer checkout whose glyphs the page draws. Inside the main repo
// that is two levels up; once the landing page lives on its own, point
// DESIGNLAYER_REPO at a clone of phil8-li/design-layer.
const repo = path.resolve(process.env.DESIGNLAYER_REPO ?? path.join(here, "..", ".."))
const require = createRequire(import.meta.url)
const esbuild = require(path.join(repo, "node_modules", "esbuild"))

const NAMES = [
  "ArrowRight", "Check", "Code", "Component", "Copy", "Cursor", "ExternalLink",
  "Eye", "GapColumn", "Grid2x2", "Image", "ListChecks", "Lock", "MessageSquare",
  "Minimize", "PanelLeft", "PanelRight", "Pencil", "Play", "Search", "Send",
  "SpaceBetweenHorizontal", "Sparkles", "ToolUndo", "Trash", "Type", "Plus",
  "CornerRadius", "Opacity", "FlowHorizontal", "ToolRedo", "Sun", "ToolClose",
]
// The toolbar draws these filled while they are on; the sprite carries that
// weight too, as i-<Name>-filled, so the page's toolbar matches the editor's.
const FILLED = ["Cursor", "MessageSquare", "Grid2x2", "PanelLeft", "PanelRight"]

const source = fs.readFileSync(path.join(repo, "src", "core", "icons.ts"), "utf8")
const { code } = await esbuild.transform(source, { loader: "ts", format: "esm" })
const mod = await import(`data:text/javascript;base64,${Buffer.from(code).toString("base64")}`)
const icons = Object.fromEntries(mod.ICON_NAMES.map((name) => [name, null]))
// ICONS itself is not exported; drawIcon needs a DOM. Read the table through
// the one export that reaches it without a document: a tiny fake.
const shapesOf = (name, weight = "auto") => {
  const nodes = []
  const fake = {
    createElementNS: (_ns, tag) => {
      const node = { tag, attrs: {}, children: [], style: { setProperty() {} } }
      node.setAttribute = (key, value) => { node.attrs[key] = value }
      node.append = (...kids) => node.children.push(...kids)
      nodes.push(node)
      return node
    },
  }
  globalThis.document = fake
  const svg = mod.icon(name, 16, weight)
  delete globalThis.document
  return svg.children
}

const escape = (value) => String(value).replace(/&/g, "&amp;").replace(/"/g, "&quot;")
const render = (node) => {
  const attrs = Object.entries(node.attrs).map(([k, v]) => ` ${k}="${escape(v)}"`).join("")
  const kids = node.children.map(render).join("")
  return kids ? `<${node.tag}${attrs}>${kids}</${node.tag}>` : `<${node.tag}${attrs}/>`
}

const missing = NAMES.filter((name) => !(name in icons))
if (missing.length) {
  console.error(`✗ not in src/core/icons.ts: ${missing.join(", ")}`)
  process.exit(1)
}

const symbols = [
  ...NAMES.map((name) => `  <symbol id="i-${name}" viewBox="0 0 24 24">${shapesOf(name).map(render).join("")}</symbol>`),
  ...FILLED.map((name) => `  <symbol id="i-${name}-filled" viewBox="0 0 24 24"><g fill="currentColor">${shapesOf(name, "filled").map(render).join("")}</g></symbol>`),
]
const out = [
  `<!-- Generated by landing/tools/build-sprite.mjs from src/core/icons.ts. Do not edit. -->`,
  `<svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round">`,
  ...symbols,
  `</svg>`,
  ``,
].join("\n")
fs.writeFileSync(path.join(repo, "site", "assets", "icons.svg"), out)
console.log(`✓ landing/assets/icons.svg — ${NAMES.length} glyphs, ${FILLED.length} filled`)
