/**
 * The editor chrome's glyph set.
 *
 * GENERATED by `tools/build-icons.mjs` — do not hand-edit. To swap a glyph,
 * change the mapping in that script and re-run it. Drawings are Phosphor
 * 2.1.1 (https://phosphoricons.com, MIT), regular weight, with its fill
 * weight shipped for the marks a toggle draws — except 17 glyphs that keep
 * their earlier artwork (`stroke` set; see KEPT DRAWINGS in the script).
 *
 * Phosphor draws on a 256 grid; the generator rewrites each path onto the
 * shared 24x24 grid, so every glyph keeps the one `0 0 24 24` viewBox and
 * the `size` a call site asks for is exactly the box it gets.
 *
 *   - Every shape is a FILLED outline: Phosphor's line weight (1.5 of 24) is
 *     part of the path. The root stroke adds weight on top of it — a little at
 *     the small rungs, see `STROKE_FOR_SIZE`, and half a unit more on a pressed
 *     or selected control (see `css/icons.ts`).
 *
 *   - A `filled` array is Phosphor's fill weight, on the glyphs a toggle draws.
 *     A flood cannot serve a drawing that is already filled, so those carry the
 *     second weight, held by the generator to the outline's ink extent.
 */

export type IconNode = [
  tag: string,
  attrs: Record<string, string | number>,
  children?: IconNode[],
]

/**
 * One glyph: its shapes, on the shared 24 grid. `filled` is the toggle's ON
 * drawing; absent, the filled weight paints the same shapes.
 */
export interface IconData {
  shapes: IconNode[]
  filled?: IconNode[]
  /** A kept stroke-family drawing's own weight, in place of the rung table. */
  stroke?: number
}

/**
 * Which weight a glyph is asked for.
 *
 * `auto` is the outline, and lets the stylesheet add the extra stroke when the
 * control reports itself selected in a list of its peers — which is how "on
 * means heavier" stays one rule rather than 79 call sites.
 *
 * `filled` is what a TOGGLE asks for while it is on. A heavier line is a
 * relative signal: legible beside the same glyph in its off state, and
 * unreadable on a button sitting on its own, which is exactly the case a mode
 * indicator has to answer. Solid or hollow needs nothing to compare against.
 */
export type IconWeight = "outline" | "filled" | "auto"

/**
 * The only sizes a glyph may be drawn at: the kit's six icon roles in
 * `tokens.icon` — marker 12, inline 14, action 16, chrome 18, header 20,
 * feature 24.
 *
 * A union rather than `number`, so a size off the ramp fails to compile instead
 * of shipping. Call sites should pass `tokens.icon.action` and friends rather
 * than the number, which is what makes the ramp readable at the point of use;
 * this type is the backstop for the ones that do not.
 */
export type IconSize = 12 | 14 | 16 | 18 | 20 | 24

/**
 * The stroke laid over each rung's outline, in grid units.
 *
 * Phosphor's regular line is 1.5 of 24, which renders 0.75px at 12px — under
 * the 1px floor the chrome holds. A stroke of `w` on a filled outline thickens
 * every line by `w`, so the small rungs get the difference back and the large
 * ones draw Phosphor's weight untouched: 1.0px at 12, rising to 1.5px at 24.
 *
 * `tools/build-icons.mjs` measures every shape's clearance inside the grid and
 * fails the build if the heaviest stroke that renders would clip one.
 */
const STROKE_FOR_SIZE: Record<IconSize, number> = {
  12: 0.5,
  14: 0.3,
  16: 0.15,
  18: 0,
  20: 0,
  24: 0,
}

/**
 * The stroke width, published as a custom property the stylesheet can build on.
 *
 * Written ALONGSIDE the `stroke-width` attribute rather than instead of it. The
 * attribute is the value that is always right, including with no stylesheet at
 * all; the property is what lets one CSS rule say "pressed is half a unit
 * heavier" without knowing which rung the glyph was drawn at.
 */
export const ICON_STROKE_VARIABLE = "--de-icon-stroke"

/**
 * What marks an `<svg>` as one of OURS.
 *
 * The state rule in `css/icons.ts` leans on the custom property above, and
 * without this it would also reach two kinds of `<svg>` it has no business
 * restyling: the host's own icons, which `drawHostIcon` renders inside the
 * inspector exactly as their author drew them, and any `<svg>` the app being
 * edited happens to place inside a selected row.
 */
export const ICON_MARKER_ATTRIBUTE = "data-de-glyph"

const ICONS = {
  "AlignCenterHorizontal": {
    // kept: native — inks 18.0x16.5 of 24
    stroke: 2,
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 10.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 7.5,
        "y": 3,
        "width": 3,
        "height": 16.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 13.5,
        "y": 6,
        "width": 3,
        "height": 10.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "AlignCenterVertical": {
    // kept: native — inks 16.5x18.0 of 24
    stroke: 2,
    shapes: [
    [
      "rect",
      {
        "x": 10.5,
        "y": 3,
        "width": 1.5,
        "height": 18,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 7.5,
        "width": 16.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 6,
        "y": 13.5,
        "width": 10.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "AlignEndHorizontal": {
    // kept: native — inks 18.0x18.0 of 24
    stroke: 2,
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 19.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 7.5,
        "y": 3,
        "width": 3,
        "height": 13.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 13.5,
        "y": 9,
        "width": 3,
        "height": 7.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "AlignEndVertical": {
    // kept: native — inks 18.0x18.0 of 24
    stroke: 2,
    shapes: [
    [
      "rect",
      {
        "x": 19.5,
        "y": 3,
        "width": 1.5,
        "height": 18,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 7.5,
        "width": 13.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 9,
        "y": 13.5,
        "width": 7.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "AlignStartHorizontal": {
    // kept: native — inks 18.0x18.0 of 24
    stroke: 2,
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 7.5,
        "y": 7.5,
        "width": 3,
        "height": 13.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 13.5,
        "y": 7.5,
        "width": 3,
        "height": 7.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "AlignStartVertical": {
    // kept: native — inks 18.0x18.0 of 24
    stroke: 2,
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 1.5,
        "height": 18,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 7.5,
        "y": 7.5,
        "width": 13.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 7.5,
        "y": 13.5,
        "width": 7.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ArrangeBack": {
    // phosphor/arrow-line-down — inks 18.0x18.8 of 24
    shapes: [
    [
      "path",
      {
        "d": "M4.719 11.031A0.75 0.75 0 0 1 5.781 9.969L11.25 15.44L11.25 3A0.75 0.75 0 0 1 12.75 3L12.75 15.44L18.219 9.969A0.75 0.75 0 0 1 19.281 11.031L12.531 17.781A0.75 0.75 0 0 1 11.469 17.781zM20.25 19.5L3.75 19.5A0.75 0.75 0 0 0 3.75 21L20.25 21A0.75 0.75 0 0 0 20.25 19.5z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "ArrangeBackward": {
    // phosphor/arrow-down — inks 15.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M19.281 14.031L12.531 20.781A0.75 0.75 0 0 1 11.469 20.781L4.719 14.031A0.75 0.75 0 0 1 5.781 12.969L11.25 18.44L11.25 3.75A0.75 0.75 0 0 1 12.75 3.75L12.75 18.44L18.219 12.969A0.75 0.75 0 0 1 19.281 14.031z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "ArrangeForward": {
    // phosphor/arrow-up — inks 15.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M19.281 11.031A0.75 0.75 0 0 1 18.219 11.031L12.75 5.56L12.75 20.25A0.75 0.75 0 0 1 11.25 20.25L11.25 5.56L5.781 11.031A0.75 0.75 0 0 1 4.719 9.969L11.469 3.219A0.75 0.75 0 0 1 12.531 3.219L19.281 9.969A0.75 0.75 0 0 1 19.281 11.031z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "ArrangeFront": {
    // phosphor/arrow-line-up — inks 18.0x18.8 of 24
    shapes: [
    [
      "path",
      {
        "d": "M19.281 12.969A0.75 0.75 0 0 1 18.219 14.031L12.75 8.56L12.75 21A0.75 0.75 0 0 1 11.25 21L11.25 8.56L5.781 14.031A0.75 0.75 0 0 1 4.719 12.969L11.469 6.219A0.75 0.75 0 0 1 12.531 6.219zM20.25 3L3.75 3A0.75 0.75 0 0 0 3.75 4.5L20.25 4.5A0.75 0.75 0 0 0 20.25 3z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "ArrowDown": {
    // phosphor/arrow-down — inks 15.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M19.281 14.031L12.531 20.781A0.75 0.75 0 0 1 11.469 20.781L4.719 14.031A0.75 0.75 0 0 1 5.781 12.969L11.25 18.44L11.25 3.75A0.75 0.75 0 0 1 12.75 3.75L12.75 18.44L18.219 12.969A0.75 0.75 0 0 1 19.281 14.031z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "ArrowDownToLine": {
    // phosphor/arrow-line-down — inks 18.0x18.8 of 24
    shapes: [
    [
      "path",
      {
        "d": "M4.719 11.031A0.75 0.75 0 0 1 5.781 9.969L11.25 15.44L11.25 3A0.75 0.75 0 0 1 12.75 3L12.75 15.44L18.219 9.969A0.75 0.75 0 0 1 19.281 11.031L12.531 17.781A0.75 0.75 0 0 1 11.469 17.781zM20.25 19.5L3.75 19.5A0.75 0.75 0 0 0 3.75 21L20.25 21A0.75 0.75 0 0 0 20.25 19.5z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "ArrowRight": {
    // phosphor/arrow-right — inks 18.0x15.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M20.781 12.531L14.031 19.281A0.75 0.75 0 0 1 12.969 18.219L18.44 12.75L3.75 12.75A0.75 0.75 0 0 1 3.75 11.25L18.44 11.25L12.969 5.781A0.75 0.75 0 0 1 14.031 4.719L20.781 11.469A0.75 0.75 0 0 1 20.781 12.531z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "ArrowUp": {
    // phosphor/arrow-up — inks 15.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M19.281 11.031A0.75 0.75 0 0 1 18.219 11.031L12.75 5.56L12.75 20.25A0.75 0.75 0 0 1 11.25 20.25L11.25 5.56L5.781 11.031A0.75 0.75 0 0 1 4.719 9.969L11.469 3.219A0.75 0.75 0 0 1 12.531 3.219L19.281 9.969A0.75 0.75 0 0 1 19.281 11.031z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "ArrowUpToLine": {
    // phosphor/arrow-line-up — inks 18.0x18.8 of 24
    shapes: [
    [
      "path",
      {
        "d": "M19.281 12.969A0.75 0.75 0 0 1 18.219 14.031L12.75 8.56L12.75 21A0.75 0.75 0 0 1 11.25 21L11.25 8.56L5.781 14.031A0.75 0.75 0 0 1 4.719 12.969L11.469 6.219A0.75 0.75 0 0 1 12.531 6.219zM20.25 3L3.75 3A0.75 0.75 0 0 0 3.75 4.5L20.25 4.5A0.75 0.75 0 0 0 20.25 3z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "Ban": {
    // phosphor/prohibit — inks 19.5x19.5 of 24
    shapes: [
    [
      "path",
      {
        "d": "M12 2.25A9.75 9.75 0 1 0 21.75 12A9.76 9.76 0 0 0 12 2.25zM20.25 12A8.209 8.209 0 0 1 18.337 17.276L6.724 5.663A8.25 8.25 0 0 1 20.25 12zM3.75 12A8.209 8.209 0 0 1 5.663 6.724L17.276 18.337A8.25 8.25 0 0 1 3.75 12z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "Check": {
    // phosphor/check — inks 18.8x13.5 of 24
    shapes: [
    [
      "path",
      {
        "d": "M21.531 7.281L9.531 19.281A0.75 0.75 0 0 1 8.469 19.281L3.219 14.031A0.75 0.75 0 0 1 4.281 12.969L9 17.69L20.469 6.219A0.75 0.75 0 0 1 21.531 7.281z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "ChevronDown": {
    // phosphor/caret-down (×0.85) — inks 14.0x7.7 of 24
    shapes: [
    [
      "path",
      {
        "d": "M18.826 9.901L12.451 16.276A0.637 0.637 0 0 1 11.549 16.276L5.174 9.901A0.637 0.637 0 0 1 6.076 8.999L12 14.924L17.924 8.999A0.637 0.637 0 0 1 18.826 9.901z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "ChevronRight": {
    // phosphor/caret-right (×0.85) — inks 7.7x14.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M16.276 12.451L9.901 18.826A0.637 0.637 0 0 1 8.999 17.924L14.924 12L8.999 6.076A0.637 0.637 0 0 1 9.901 5.174L16.276 11.549A0.637 0.637 0 0 1 16.276 12.451z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "ChevronsDownUp": {
    // phosphor/caret-up-down (each caret turned) — inks 10.5x19.5 of 24
    shapes: [
    [
      "path",
      {
        "d": "M17.031 21.531A0.75 0.75 0 0 0 17.031 20.469L12.531 15.969A0.75 0.75 0 0 0 11.469 15.969L6.969 20.469A0.75 0.75 0 0 0 8.031 21.531L12 17.56L15.969 21.531A0.75 0.75 0 0 0 17.031 21.531zM8.031 2.469L12 6.44L15.969 2.469A0.75 0.75 0 0 1 17.031 3.53L12.531 8.03A0.75 0.75 0 0 1 11.469 8.03L6.969 3.53A0.75 0.75 0 0 1 8.031 2.469z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "ChevronsUpDown": {
    // phosphor/caret-up-down — inks 10.5x19.5 of 24
    shapes: [
    [
      "path",
      {
        "d": "M17.031 15.969A0.75 0.75 0 0 1 17.031 17.031L12.531 21.531A0.75 0.75 0 0 1 11.469 21.531L6.969 17.031A0.75 0.75 0 0 1 8.031 15.969L12 19.94L15.969 15.969A0.75 0.75 0 0 1 17.031 15.969zM8.031 8.031L12 4.06L15.969 8.031A0.75 0.75 0 0 0 17.031 6.969L12.531 2.469A0.75 0.75 0 0 0 11.469 2.469L6.969 6.969A0.75 0.75 0 0 0 8.031 8.031z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "Circle": {
    // phosphor/circle — inks 19.5x19.5 of 24
    shapes: [
    [
      "path",
      {
        "d": "M12 2.25A9.75 9.75 0 1 0 21.75 12A9.76 9.76 0 0 0 12 2.25zM12 20.25A8.25 8.25 0 1 1 20.25 12A8.259 8.259 0 0 1 12 20.25z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "Code": {
    // phosphor/code (×0.9) — inks 20.2x16.2 of 24
    shapes: [
    [
      "path",
      {
        "d": "M7.032 9.144L3.605 12L7.032 14.856A0.675 0.675 0 1 1 6.168 15.893L2.118 12.518A0.675 0.675 0 0 1 2.118 11.481L6.168 8.106A0.675 0.675 0 0 1 7.032 9.144zM21.882 11.481L17.832 8.106A0.675 0.675 0 1 0 16.968 9.144L20.395 12L16.968 14.856A0.675 0.675 0 1 0 17.832 15.893L21.882 12.518A0.675 0.675 0 0 0 21.882 11.481zM14.93 3.94A0.675 0.675 0 0 0 14.065 4.345L8.665 19.195A0.675 0.675 0 0 0 9.07 20.06A0.687 0.687 0 0 0 9.3 20.1A0.675 0.675 0 0 0 9.934 19.655L15.335 4.805A0.675 0.675 0 0 0 14.93 3.94z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "Component": {
    // phosphor/diamonds-four — inks 21.0x21.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M11.469 10.281A0.75 0.75 0 0 0 12.531 10.281L16.281 6.531A0.75 0.75 0 0 0 16.281 5.469L12.531 1.719A0.75 0.75 0 0 0 11.469 1.719L7.719 5.469A0.75 0.75 0 0 0 7.719 6.531zM12 3.31L14.69 6L12 8.69L9.31 6zM12.531 13.717A0.75 0.75 0 0 0 11.469 13.717L7.719 17.467A0.75 0.75 0 0 0 7.719 18.528L11.469 22.278A0.75 0.75 0 0 0 12.531 22.278L16.281 18.528A0.75 0.75 0 0 0 16.281 17.467zM12 20.69L9.31 18L12 15.31L14.69 18zM22.281 11.469L18.531 7.719A0.75 0.75 0 0 0 17.469 7.719L13.719 11.469A0.75 0.75 0 0 0 13.719 12.531L17.469 16.281A0.75 0.75 0 0 0 18.531 16.281L22.281 12.531A0.75 0.75 0 0 0 22.281 11.469zM18 14.69L15.31 12L18 9.31L20.69 12zM10.281 11.469L6.531 7.719A0.75 0.75 0 0 0 5.469 7.719L1.719 11.469A0.75 0.75 0 0 0 1.719 12.531L5.469 16.281A0.75 0.75 0 0 0 6.531 16.281L10.281 12.531A0.75 0.75 0 0 0 10.281 11.469zM6 14.69L3.31 12L6 9.31L8.69 12z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "Constrain": {
    // phosphor/link-simple — inks 19.5x19.5 of 24
    shapes: [
    [
      "path",
      {
        "d": "M15.531 8.469A0.75 0.75 0 0 1 15.531 9.531L9.531 15.531A0.75 0.75 0 0 1 8.469 14.469L14.469 8.469A0.75 0.75 0 0 1 15.531 8.469zM20.212 3.788A5.25 5.25 0 0 0 12.788 3.788L9.969 6.605A0.75 0.75 0 0 0 11.031 7.666L13.849 4.853A3.75 3.75 0 0 1 19.152 10.156L16.333 12.974A0.75 0.75 0 0 0 17.393 14.035L20.212 11.212A5.25 5.25 0 0 0 20.212 3.788zM12.969 16.333L10.151 19.151A3.75 3.75 0 1 1 4.849 13.848L7.666 11.031A0.75 0.75 0 0 0 6.605 9.969L3.788 12.788A5.25 5.25 0 0 0 11.212 20.212L14.031 17.393A0.75 0.75 0 0 0 12.969 16.333z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "Copy": {
    // phosphor/copy — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M20.25 3L8.25 3A0.75 0.75 0 0 0 7.5 3.75L7.5 7.5L3.75 7.5A0.75 0.75 0 0 0 3 8.25L3 20.25A0.75 0.75 0 0 0 3.75 21L15.75 21A0.75 0.75 0 0 0 16.5 20.25L16.5 16.5L20.25 16.5A0.75 0.75 0 0 0 21 15.75L21 3.75A0.75 0.75 0 0 0 20.25 3zM15 19.5L4.5 19.5L4.5 9L15 9zM19.5 15L16.5 15L16.5 8.25A0.75 0.75 0 0 0 15.75 7.5L9 7.5L9 4.5L19.5 4.5z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "CornerRadius": {
    // native (drawn in phosphor's construction) — inks 16.5x16.5 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5.25 21L5.25 12A6.75 6.75 0 0 1 12 5.25L21 5.25A0.75 0.75 0 0 1 21 6.75L12 6.75A5.25 5.25 0 0 0 6.75 12L6.75 21A0.75 0.75 0 0 1 5.25 21z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "Cursor": {
    // phosphor/cursor — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M15.75 12.44L20.07 10.781L20.101 10.769A1.5 1.5 0 0 0 19.969 7.975L4.961 3.075A1.495 1.495 0 0 0 3.075 4.961L7.975 19.969A1.483 1.483 0 0 0 9.326 21L9.399 21A1.485 1.485 0 0 0 10.769 20.101L10.781 20.07L12.44 15.75L17.25 20.56A1.5 1.5 0 0 0 19.372 20.56L20.56 19.372A1.5 1.5 0 0 0 20.56 17.25zM18.31 19.5L13.5 14.69A1.5 1.5 0 0 0 11.063 15.152C11.063 15.162 11.054 15.172 11.05 15.182L9.396 19.494L4.5 4.5L19.486 9.394L15.178 11.047L15.148 11.06A1.5 1.5 0 0 0 14.686 13.497L14.686 13.497L19.5 18.31z",
        "fill": "currentColor",
      },
    ],
    ],
    // filled — inks 18.0x18.0 of 24
    filled: [
    [
      "path",
      {
        "d": "M20.671 19.481L19.481 20.671A1.125 1.125 0 0 1 17.888 20.671L12.584 15.367L10.781 20.07L10.769 20.101A1.485 1.485 0 0 1 9.399 21L9.326 21A1.483 1.483 0 0 1 7.975 19.969L3.075 4.961A1.495 1.495 0 0 1 4.961 3.075L19.969 7.975A1.5 1.5 0 0 1 20.101 10.769L20.07 10.781L15.367 12.588L20.671 17.89A1.125 1.125 0 0 1 20.671 19.481z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "ExternalLink": {
    // kept: foundations/external-link, fitted ×0.909 — inks 20.0x20.0 of 24
    stroke: 2,
    shapes: [
    [
      "path",
      {
        "d": "M21.0909 13.8182A0.9091 0.9091 0 0 0 20.1818 14.7273L20.1818 18.3636A1.82 1.82 0 0 1 18.3636 20.1818L5.6364 20.1818A1.82 1.82 0 0 1 3.8182 18.3636L3.8182 5.6364A1.82 1.82 0 0 1 5.6364 3.8182L9.2727 3.8182A0.9091 0.9091 0 0 0 9.2727 2L5.6364 2A3.64 3.64 0 0 0 2 5.6364L2 18.3636A3.64 3.64 0 0 0 5.6364 22L18.3636 22A3.64 3.64 0 0 0 22 18.3636L22 14.7273A0.9091 0.9091 0 0 0 21.0909 13.8182zM21.0909 2L14.7273 2A0.9091 0.9091 0 0 0 14.7273 3.8182L18.8964 3.8182L7.7209 14.9936A0.9091 0.9091 0 1 0 9.0064 16.2791L20.1818 5.1036L20.1818 9.2727A0.9091 0.9091 0 0 0 22 9.2727L22 2.9091A0.9091 0.9091 0 0 0 21.0909 2z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Eye": {
    // phosphor/eye — inks 22.5x15.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M23.185 11.696C23.152 11.622 22.358 9.861 20.593 8.095C18.241 5.743 15.27 4.5 12 4.5S5.759 5.743 3.407 8.095C1.642 9.861 0.844 11.625 0.815 11.696A0.75 0.75 0 0 0 0.815 12.306C0.847 12.38 1.642 14.14 3.407 15.906C5.759 18.257 8.73 19.5 12 19.5S18.241 18.257 20.593 15.906C22.358 14.14 23.152 12.38 23.185 12.306A0.75 0.75 0 0 0 23.185 11.696zM12 18C9.114 18 6.593 16.951 4.507 14.883A12.513 12.513 0 0 1 2.344 12A12.5 12.5 0 0 1 4.507 9.117C6.593 7.049 9.114 6 12 6S17.407 7.049 19.493 9.117A12.512 12.512 0 0 1 21.661 12C20.985 13.262 18.04 18 12 18zM12 7.5A4.5 4.5 0 1 0 16.5 12A4.505 4.505 0 0 0 12 7.5zM12 15A3 3 0 1 1 15 12A3 3 0 0 1 12 15z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "EyeOff": {
    // phosphor/eye-slash — inks 22.5x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5.055 3.246A0.75 0.75 0 1 0 3.945 4.254L5.749 6.239C2.344 8.329 0.879 11.55 0.815 11.696A0.75 0.75 0 0 0 0.815 12.306C0.847 12.38 1.642 14.14 3.407 15.906C5.759 18.257 8.73 19.5 12 19.5A11.917 11.917 0 0 0 16.882 18.485L18.944 20.754A0.75 0.75 0 1 0 20.054 19.746zM9.492 10.356L13.399 14.654A3 3 0 0 1 9.492 10.356zM12 18C9.114 18 6.593 16.951 4.507 14.883A12.484 12.484 0 0 1 2.344 12C2.783 11.176 4.187 8.87 6.783 7.371L8.47 9.222A4.5 4.5 0 0 0 14.438 15.785L15.819 17.303A10.5 10.5 0 0 1 12 18zM12.563 9.053A0.75 0.75 0 0 1 12.844 7.58A4.515 4.515 0 0 1 16.478 11.577A0.75 0.75 0 0 1 15.802 12.394A0.599 0.599 0 0 1 15.731 12.394A0.75 0.75 0 0 1 14.981 11.713A3.008 3.008 0 0 0 12.563 9.053zM23.183 12.306C23.143 12.394 22.193 14.497 20.055 16.412A0.75 0.75 0 1 1 19.055 15.294A12.447 12.447 0 0 0 21.661 12A12.483 12.483 0 0 0 19.493 9.115C17.407 7.049 14.886 6 12 6A11.097 11.097 0 0 0 10.185 6.147A0.75 0.75 0 1 1 9.938 4.668A12.563 12.563 0 0 1 12 4.5C15.27 4.5 18.241 5.743 20.593 8.095C22.358 9.861 23.152 11.622 23.185 11.696A0.75 0.75 0 0 1 23.185 12.306z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "EyeOpen": {
    // phosphor/eye — inks 22.5x15.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M23.185 11.696C23.152 11.622 22.358 9.861 20.593 8.095C18.241 5.743 15.27 4.5 12 4.5S5.759 5.743 3.407 8.095C1.642 9.861 0.844 11.625 0.815 11.696A0.75 0.75 0 0 0 0.815 12.306C0.847 12.38 1.642 14.14 3.407 15.906C5.759 18.257 8.73 19.5 12 19.5S18.241 18.257 20.593 15.906C22.358 14.14 23.152 12.38 23.185 12.306A0.75 0.75 0 0 0 23.185 11.696zM12 18C9.114 18 6.593 16.951 4.507 14.883A12.513 12.513 0 0 1 2.344 12A12.5 12.5 0 0 1 4.507 9.117C6.593 7.049 9.114 6 12 6S17.407 7.049 19.493 9.117A12.512 12.512 0 0 1 21.661 12C20.985 13.262 18.04 18 12 18zM12 7.5A4.5 4.5 0 1 0 16.5 12A4.505 4.505 0 0 0 12 7.5zM12 15A3 3 0 1 1 15 12A3 3 0 0 1 12 15z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "FlowHorizontal": {
    // phosphor/columns — inks 15.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M9.75 3L6 3A1.5 1.5 0 0 0 4.5 4.5L4.5 19.5A1.5 1.5 0 0 0 6 21L9.75 21A1.5 1.5 0 0 0 11.25 19.5L11.25 4.5A1.5 1.5 0 0 0 9.75 3zM9.75 19.5L6 19.5L6 4.5L9.75 4.5zM18 3L14.25 3A1.5 1.5 0 0 0 12.75 4.5L12.75 19.5A1.5 1.5 0 0 0 14.25 21L18 21A1.5 1.5 0 0 0 19.5 19.5L19.5 4.5A1.5 1.5 0 0 0 18 3zM18 19.5L14.25 19.5L14.25 4.5L18 4.5z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "FlowNone": {
    // phosphor/prohibit — inks 19.5x19.5 of 24
    shapes: [
    [
      "path",
      {
        "d": "M12 2.25A9.75 9.75 0 1 0 21.75 12A9.76 9.76 0 0 0 12 2.25zM20.25 12A8.209 8.209 0 0 1 18.337 17.276L6.724 5.663A8.25 8.25 0 0 1 20.25 12zM3.75 12A8.209 8.209 0 0 1 5.663 6.724L17.276 18.337A8.25 8.25 0 0 1 3.75 12z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "FlowVertical": {
    // phosphor/rows — inks 18.0x15.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M19.5 12.75L4.5 12.75A1.5 1.5 0 0 0 3 14.25L3 18A1.5 1.5 0 0 0 4.5 19.5L19.5 19.5A1.5 1.5 0 0 0 21 18L21 14.25A1.5 1.5 0 0 0 19.5 12.75zM19.5 18L4.5 18L4.5 14.25L19.5 14.25L19.5 18zM19.5 4.5L4.5 4.5A1.5 1.5 0 0 0 3 6L3 9.75A1.5 1.5 0 0 0 4.5 11.25L19.5 11.25A1.5 1.5 0 0 0 21 9.75L21 6A1.5 1.5 0 0 0 19.5 4.5zM19.5 9.75L4.5 9.75L4.5 6L19.5 6L19.5 9.75z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "FlowWrap": {
    // phosphor/squares-four — inks 16.5x16.5 of 24
    shapes: [
    [
      "path",
      {
        "d": "M9.75 3.75L5.25 3.75A1.5 1.5 0 0 0 3.75 5.25L3.75 9.75A1.5 1.5 0 0 0 5.25 11.25L9.75 11.25A1.5 1.5 0 0 0 11.25 9.75L11.25 5.25A1.5 1.5 0 0 0 9.75 3.75zM9.75 9.75L5.25 9.75L5.25 5.25L9.75 5.25L9.75 9.75zM18.75 3.75L14.25 3.75A1.5 1.5 0 0 0 12.75 5.25L12.75 9.75A1.5 1.5 0 0 0 14.25 11.25L18.75 11.25A1.5 1.5 0 0 0 20.25 9.75L20.25 5.25A1.5 1.5 0 0 0 18.75 3.75zM18.75 9.75L14.25 9.75L14.25 5.25L18.75 5.25L18.75 9.75zM9.75 12.75L5.25 12.75A1.5 1.5 0 0 0 3.75 14.25L3.75 18.75A1.5 1.5 0 0 0 5.25 20.25L9.75 20.25A1.5 1.5 0 0 0 11.25 18.75L11.25 14.25A1.5 1.5 0 0 0 9.75 12.75zM9.75 18.75L5.25 18.75L5.25 14.25L9.75 14.25L9.75 18.75zM18.75 12.75L14.25 12.75A1.5 1.5 0 0 0 12.75 14.25L12.75 18.75A1.5 1.5 0 0 0 14.25 20.25L18.75 20.25A1.5 1.5 0 0 0 20.25 18.75L20.25 14.25A1.5 1.5 0 0 0 18.75 12.75zM18.75 18.75L14.25 18.75L14.25 14.25L18.75 14.25L18.75 18.75z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "GapColumn": {
    // phosphor/split-horizontal (×0.86) — inks 18.1x14.2 of 24
    shapes: [
    [
      "path",
      {
        "d": "M10.71 5.55L10.71 18.45A0.645 0.645 0 0 1 9.42 18.45L9.42 12.645L5.172 12.645L6.651 14.124A0.645 0.645 0 0 1 5.739 15.036L3.159 12.456A0.645 0.645 0 0 1 3.159 11.544L5.739 8.964A0.645 0.645 0 0 1 6.651 9.876L5.172 11.355L9.42 11.355L9.42 5.55A0.645 0.645 0 0 1 10.71 5.55zM20.841 11.544L18.261 8.964A0.645 0.645 0 0 0 17.349 9.876L18.828 11.355L14.58 11.355L14.58 5.55A0.645 0.645 0 0 0 13.29 5.55L13.29 18.45A0.645 0.645 0 0 0 14.58 18.45L14.58 12.645L18.828 12.645L17.349 14.124A0.645 0.645 0 0 0 18.261 15.036L20.841 12.456A0.645 0.645 0 0 0 20.841 11.544z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "GapRow": {
    // phosphor/split-vertical (×0.86) — inks 14.2x18.1 of 24
    shapes: [
    [
      "path",
      {
        "d": "M19.095 13.935A0.645 0.645 0 0 1 18.45 14.58L12.645 14.58L12.645 18.828L14.124 17.349A0.645 0.645 0 0 1 15.036 18.261L12.456 20.841A0.645 0.645 0 0 1 11.544 20.841L8.964 18.261A0.645 0.645 0 0 1 9.876 17.349L11.355 18.828L11.355 14.58L5.55 14.58A0.645 0.645 0 0 1 5.55 13.29L18.45 13.29A0.645 0.645 0 0 1 19.095 13.935zM5.55 10.71L18.45 10.71A0.645 0.645 0 0 0 18.45 9.42L12.645 9.42L12.645 5.172L14.124 6.651A0.645 0.645 0 0 0 15.036 5.739L12.456 3.159A0.645 0.645 0 0 0 11.544 3.159L8.964 5.739A0.645 0.645 0 0 0 9.876 6.651L11.355 5.172L11.355 9.42L5.55 9.42A0.645 0.645 0 0 0 5.55 10.71z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "Grid2x2": {
    // kept: lucide/Grid2x2 — inks 16.2x16.2 of 24
    stroke: 2,
    shapes: [
    [
      "path",
      {
        "d": "M12 3.9L12 20.1",
      },
    ],
    [
      "path",
      {
        "d": "M3.9 12L20.1 12",
      },
    ],
    [
      "rect",
      {
        "x": 3.9000000000000004,
        "y": 3.9000000000000004,
        "width": 16.200000000000003,
        "height": 16.200000000000003,
        "rx": 1.8,
      },
    ],
    ],
    // filled — inks 18.0x18.0 of 24
    filled: [
    [
      "path",
      {
        "d": "M4.5 3h5a1.5 1.5 0 0 1 1.5 1.5v5a1.5 1.5 0 0 1 -1.5 1.5h-5a1.5 1.5 0 0 1 -1.5 -1.5v-5a1.5 1.5 0 0 1 1.5 -1.5zM4.5 13h5a1.5 1.5 0 0 1 1.5 1.5v5a1.5 1.5 0 0 1 -1.5 1.5h-5a1.5 1.5 0 0 1 -1.5 -1.5v-5a1.5 1.5 0 0 1 1.5 -1.5zM14.5 3h5a1.5 1.5 0 0 1 1.5 1.5v5a1.5 1.5 0 0 1 -1.5 1.5h-5a1.5 1.5 0 0 1 -1.5 -1.5v-5a1.5 1.5 0 0 1 1.5 -1.5zM14.5 13h5a1.5 1.5 0 0 1 1.5 1.5v5a1.5 1.5 0 0 1 -1.5 1.5h-5a1.5 1.5 0 0 1 -1.5 -1.5v-5a1.5 1.5 0 0 1 1.5 -1.5z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Image": {
    // phosphor/image — inks 19.5x16.5 of 24
    shapes: [
    [
      "path",
      {
        "d": "M20.25 3.75L3.75 3.75A1.5 1.5 0 0 0 2.25 5.25L2.25 18.75A1.5 1.5 0 0 0 3.75 20.25L20.25 20.25A1.5 1.5 0 0 0 21.75 18.75L21.75 5.25A1.5 1.5 0 0 0 20.25 3.75zM20.25 5.25L20.25 14.883L17.806 12.44A1.5 1.5 0 0 0 15.684 12.44L13.809 14.315L9.684 10.19A1.5 1.5 0 0 0 7.564 10.19L3.75 14.003L3.75 5.25zM3.75 16.125L8.625 11.25L16.125 18.75L3.75 18.75zM20.25 18.75L18.247 18.75L14.872 15.375L16.747 13.5L20.25 17.004L20.25 18.75zM13.5 9.375A1.125 1.125 0 1 1 14.625 10.5A1.125 1.125 0 0 1 13.5 9.375z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "ListChecks": {
    // phosphor/list-checks — inks 18.0x16.5 of 24
    shapes: [
    [
      "path",
      {
        "d": "M21 12A0.75 0.75 0 0 1 20.25 12.75L12 12.75A0.75 0.75 0 0 1 12 11.25L20.25 11.25A0.75 0.75 0 0 1 21 12zM12 6.75L20.25 6.75A0.75 0.75 0 0 0 20.25 5.25L12 5.25A0.75 0.75 0 0 0 12 6.75zM20.25 17.25L12 17.25A0.75 0.75 0 0 0 12 18.75L20.25 18.75A0.75 0.75 0 0 0 20.25 17.25zM7.719 3.969L5.25 6.44L4.281 5.469A0.75 0.75 0 0 0 3.219 6.531L4.719 8.031A0.75 0.75 0 0 0 5.781 8.031L8.781 5.031A0.75 0.75 0 0 0 7.719 3.969zM7.719 9.969L5.25 12.44L4.281 11.469A0.75 0.75 0 0 0 3.219 12.531L4.719 14.031A0.75 0.75 0 0 0 5.781 14.031L8.781 11.031A0.75 0.75 0 0 0 7.719 9.969zM7.719 15.969L5.25 18.44L4.281 17.469A0.75 0.75 0 0 0 3.219 18.531L4.719 20.031A0.75 0.75 0 0 0 5.781 20.031L8.781 17.031A0.75 0.75 0 0 0 7.719 15.969z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "Lock": {
    // phosphor/lock-simple — inks 18.0x20.3 of 24
    shapes: [
    [
      "path",
      {
        "d": "M19.5 7.5L16.5 7.5L16.5 5.25A4.5 4.5 0 0 0 7.5 5.25L7.5 7.5L4.5 7.5A1.5 1.5 0 0 0 3 9L3 19.5A1.5 1.5 0 0 0 4.5 21L19.5 21A1.5 1.5 0 0 0 21 19.5L21 9A1.5 1.5 0 0 0 19.5 7.5zM9 5.25A3 3 0 0 1 15 5.25L15 7.5L9 7.5zM19.5 19.5L4.5 19.5L4.5 9L19.5 9L19.5 19.5z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "LockOpen": {
    // phosphor/lock-simple-open — inks 18.0x20.3 of 24
    shapes: [
    [
      "path",
      {
        "d": "M19.5 7.5L9 7.5L9 5.25A3 3 0 0 1 12 2.25C13.441 2.25 14.737 3.281 15.015 4.649A0.75 0.75 0 0 0 16.485 4.351C16.061 2.264 14.175 0.75 12 0.75A4.505 4.505 0 0 0 7.5 5.25L7.5 7.5L4.5 7.5A1.5 1.5 0 0 0 3 9L3 19.5A1.5 1.5 0 0 0 4.5 21L19.5 21A1.5 1.5 0 0 0 21 19.5L21 9A1.5 1.5 0 0 0 19.5 7.5zM19.5 19.5L4.5 19.5L4.5 9L19.5 9L19.5 19.5z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "MessageSquare": {
    // kept: foundations/message-square — inks 15.6x15.6 of 24
    stroke: 2,
    shapes: [
    [
      "path",
      {
        "d": "M18.7517 15.9062A7.7945 7.7945 0 1 0 15.9515 18.7259L19.8 19.8z",
      },
    ],
    ],
  },
  "Minimize": {
    // phosphor/corners-in (×1.2) — inks 19.8x19.8 of 24
    shapes: [
    [
      "path",
      {
        "d": "M14.7 8.4L14.7 3A0.9 0.9 0 0 1 16.5 3L16.5 7.5L21 7.5A0.9 0.9 0 0 1 21 9.3L15.6 9.3A0.9 0.9 0 0 1 14.7 8.4zM8.4 14.7L3 14.7A0.9 0.9 0 0 0 3 16.5L7.5 16.5L7.5 21A0.9 0.9 0 0 0 9.3 21L9.3 15.6A0.9 0.9 0 0 0 8.4 14.7zM21 14.7L15.6 14.7A0.9 0.9 0 0 0 14.7 15.6L14.7 21A0.9 0.9 0 0 0 16.5 21L16.5 16.5L21 16.5A0.9 0.9 0 0 0 21 14.7zM8.4 2.1A0.9 0.9 0 0 0 7.5 3L7.5 7.5L3 7.5A0.9 0.9 0 0 0 3 9.3L8.4 9.3A0.9 0.9 0 0 0 9.3 8.4L9.3 3A0.9 0.9 0 0 0 8.4 2.1z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "Minus": {
    // phosphor/minus (×0.89) — inks 16.0x1.3 of 24
    shapes: [
    [
      "path",
      {
        "d": "M20.01 12A0.667 0.667 0 0 1 19.343 12.668L4.657 12.668A0.667 0.667 0 0 1 4.657 11.332L19.343 11.332A0.667 0.667 0 0 1 20.01 12z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "Moon": {
    // kept: lucide/Moon — inks 18.0x18.0 of 24
    stroke: 2,
    shapes: [
    [
      "path",
      {
        "d": "M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401",
      },
    ],
    ],
  },
  "Opacity": {
    // phosphor/drop-half (×0.86) — inks 14.2x18.1 of 24
    shapes: [
    [
      "path",
      {
        "d": "M15.709 5.53A20.494 20.494 0 0 0 12.367 2.442A0.645 0.645 0 0 0 11.627 2.442A20.494 20.494 0 0 0 8.291 5.53C6.075 8.075 4.905 10.758 4.905 13.29A7.095 7.095 0 0 0 19.095 13.29C19.095 10.758 17.925 8.075 15.709 5.53zM17.805 13.29A5.69 5.69 0 0 1 17.768 13.935L12.645 13.935L12.645 12.645L17.776 12.645Q17.805 12.967 17.805 13.29zM16.466 8.775L12.645 8.775L12.645 7.485L15.619 7.485A14.178 14.178 0 0 1 16.466 8.775zM12.645 17.805L15.643 17.805A5.778 5.778 0 0 1 12.645 19.058zM12.645 16.515L12.645 15.225L17.472 15.225A5.805 5.805 0 0 1 16.827 16.515zM12.645 11.355L12.645 10.065L17.111 10.065A9.42 9.42 0 0 1 17.55 11.355zM14.571 6.195L12.645 6.195L12.645 4.308A20.738 20.738 0 0 1 14.571 6.195zM6.195 13.29C6.195 9.259 9.602 5.815 11.355 4.308L11.355 19.058A5.811 5.811 0 0 1 6.195 13.29z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "PadBottom": {
    // phosphor/square (turned -90°, plus a drawn line) — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M3 4.5L3 19.5A1.5 1.5 -90 0 0 4.5 21L19.5 21A1.5 1.5 -90 0 0 21 19.5L21 4.5A1.5 1.5 -90 0 0 19.5 3L4.5 3A1.5 1.5 -90 0 0 3 4.5zM19.5 4.5L19.5 19.5L4.5 19.5L4.5 4.5L19.5 4.5z",
        "fill": "currentColor",
      },
    ],
    [
      "path",
      {
        "d": "M4.5 19.5L4.5 18L19.5 18L19.5 19.5z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "PadLeft": {
    // phosphor/square (plus a drawn line) — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M19.5 3L4.5 3A1.5 1.5 0 0 0 3 4.5L3 19.5A1.5 1.5 0 0 0 4.5 21L19.5 21A1.5 1.5 0 0 0 21 19.5L21 4.5A1.5 1.5 0 0 0 19.5 3zM19.5 19.5L4.5 19.5L4.5 4.5L19.5 4.5L19.5 19.5z",
        "fill": "currentColor",
      },
    ],
    [
      "path",
      {
        "d": "M4.5 4.5L6 4.5L6 19.5L4.5 19.5z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "PadRight": {
    // phosphor/square (mirrored, plus a drawn line) — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M4.5 3L19.5 3A1.5 1.5 0 0 1 21 4.5L21 19.5A1.5 1.5 0 0 1 19.5 21L4.5 21A1.5 1.5 0 0 1 3 19.5L3 4.5A1.5 1.5 0 0 1 4.5 3zM4.5 19.5L19.5 19.5L19.5 4.5L4.5 4.5L4.5 19.5z",
        "fill": "currentColor",
      },
    ],
    [
      "path",
      {
        "d": "M19.5 4.5L18 4.5L18 19.5L19.5 19.5z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "PadTop": {
    // phosphor/square (turned 90°, plus a drawn line) — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M21 19.5L21 4.5A1.5 1.5 90 0 0 19.5 3L4.5 3A1.5 1.5 90 0 0 3 4.5L3 19.5A1.5 1.5 90 0 0 4.5 21L19.5 21A1.5 1.5 90 0 0 21 19.5zM4.5 19.5L4.5 4.5L19.5 4.5L19.5 19.5L4.5 19.5z",
        "fill": "currentColor",
      },
    ],
    [
      "path",
      {
        "d": "M19.5 4.5L19.5 6L4.5 6L4.5 4.5z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "PanelLeft": {
    // kept: native — inks 18.0x18.0 of 24
    stroke: 2,
    shapes: [
    [
      "path",
      {
        "d": "M6.75 3h10.5a3.75 3.75 0 0 1 3.75 3.75v10.5a3.75 3.75 0 0 1 -3.75 3.75h-10.5a3.75 3.75 0 0 1 -3.75 -3.75v-10.5a3.75 3.75 0 0 1 3.75 -3.75zM6.75 5.25h10.5a1.5 1.5 0 0 1 1.5 1.5v10.5a1.5 1.5 0 0 1 -1.5 1.5h-10.5a1.5 1.5 0 0 1 -1.5 -1.5v-10.5a1.5 1.5 0 0 1 1.5 -1.5z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 9,
        "y": 5.25,
        "width": 2.25,
        "height": 13.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
    // filled — inks 18.0x18.0 of 24
    filled: [
    [
      "path",
      {
        "d": "M6.75 3h10.5a3.75 3.75 0 0 1 3.75 3.75v10.5a3.75 3.75 0 0 1 -3.75 3.75h-10.5a3.75 3.75 0 0 1 -3.75 -3.75v-10.5a3.75 3.75 0 0 1 3.75 -3.75zM6.75 5.25h10.5a1.5 1.5 0 0 1 1.5 1.5v10.5a1.5 1.5 0 0 1 -1.5 1.5h-10.5a1.5 1.5 0 0 1 -1.5 -1.5v-10.5a1.5 1.5 0 0 1 1.5 -1.5z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 5.25h4.5v13.5h-4.5a1.5 1.5 0 0 1 -1.5 -1.5v-10.5a1.5 1.5 0 0 1 1.5 -1.5z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "PanelRight": {
    // kept: native — inks 18.0x18.0 of 24
    stroke: 2,
    shapes: [
    [
      "path",
      {
        "d": "M6.75 3h10.5a3.75 3.75 0 0 1 3.75 3.75v10.5a3.75 3.75 0 0 1 -3.75 3.75h-10.5a3.75 3.75 0 0 1 -3.75 -3.75v-10.5a3.75 3.75 0 0 1 3.75 -3.75zM6.75 5.25h10.5a1.5 1.5 0 0 1 1.5 1.5v10.5a1.5 1.5 0 0 1 -1.5 1.5h-10.5a1.5 1.5 0 0 1 -1.5 -1.5v-10.5a1.5 1.5 0 0 1 1.5 -1.5z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 12.75,
        "y": 5.25,
        "width": 2.25,
        "height": 13.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
    // filled — inks 18.0x18.0 of 24
    filled: [
    [
      "path",
      {
        "d": "M6.75 3h10.5a3.75 3.75 0 0 1 3.75 3.75v10.5a3.75 3.75 0 0 1 -3.75 3.75h-10.5a3.75 3.75 0 0 1 -3.75 -3.75v-10.5a3.75 3.75 0 0 1 3.75 -3.75zM6.75 5.25h10.5a1.5 1.5 0 0 1 1.5 1.5v10.5a1.5 1.5 0 0 1 -1.5 1.5h-10.5a1.5 1.5 0 0 1 -1.5 -1.5v-10.5a1.5 1.5 0 0 1 1.5 -1.5z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M12.75 5.25h4.5a1.5 1.5 0 0 1 1.5 1.5v10.5a1.5 1.5 0 0 1 -1.5 1.5h-4.5z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Pencil": {
    // phosphor/pencil-simple — inks 18.7x18.8 of 24
    shapes: [
    [
      "path",
      {
        "d": "M21.31 6.878L17.122 2.689A1.5 1.5 0 0 0 15 2.689L3.44 14.25A1.487 1.487 0 0 0 3 15.31L3 19.5A1.5 1.5 0 0 0 4.5 21L8.69 21A1.487 1.487 0 0 0 9.75 20.56L21.31 9A1.5 1.5 0 0 0 21.31 6.878zM8.69 19.5L4.5 19.5L4.5 15.31L12.75 7.06L16.94 11.25zM18 10.189L13.81 6L16.06 3.75L20.25 7.939z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "Play": {
    // phosphor/play — inks 16.5x19.5 of 24
    shapes: [
    [
      "path",
      {
        "d": "M21.788 10.733L8.28 2.47A1.5 1.5 0 0 0 6.761 2.442A1.487 1.487 0 0 0 6 3.738L6 20.262A1.494 1.494 0 0 0 7.5 21.75A1.507 1.507 0 0 0 8.284 21.53L21.788 13.267A1.482 1.482 0 0 0 21.788 10.735zM7.5 20.244L7.5 3.75L20.984 12z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "Plus": {
    // phosphor/plus (×0.89) — inks 16.0x16.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M20.01 12A0.667 0.667 0 0 1 19.343 12.668L12.668 12.668L12.668 19.343A0.667 0.667 0 0 1 11.332 19.343L11.332 12.668L4.657 12.668A0.667 0.667 0 0 1 4.657 11.332L11.332 11.332L11.332 4.657A0.667 0.667 0 0 1 12.668 4.657L12.668 11.332L19.343 11.332A0.667 0.667 0 0 1 20.01 12z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "Search": {
    // phosphor/magnifying-glass — inks 19.5x19.5 of 24
    shapes: [
    [
      "path",
      {
        "d": "M21.531 20.469L16.837 15.776A8.26 8.26 0 1 0 15.776 16.837L20.469 21.531A0.75 0.75 0 0 0 21.531 20.469zM3.75 10.5A6.75 6.75 0 1 1 10.5 17.25A6.758 6.758 0 0 1 3.75 10.5z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "Send": {
    // phosphor/paper-plane-tilt — inks 21.0x21.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M21.311 2.689A1.5 1.5 0 0 0 19.843 2.306L19.829 2.306L1.835 7.766A1.5 1.5 0 0 0 1.601 10.56L9.563 14.438L13.434 22.394A1.487 1.487 0 0 0 14.788 23.25Q14.853 23.25 14.918 23.244A1.489 1.489 0 0 0 16.23 22.165L21.686 4.171C21.686 4.166 21.686 4.162 21.686 4.157A1.5 1.5 0 0 0 21.311 2.689zM14.797 21.736L14.792 21.749L14.792 21.742L11.036 14.027L15.536 9.527A0.75 0.75 0 0 0 14.476 8.467L9.976 12.967L2.257 9.211L2.251 9.211L2.264 9.211L20.25 3.75z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "SpaceBetweenHorizontal": {
    // phosphor/arrows-out-line-horizontal (×0.8) — inks 18.0x14.4 of 24
    shapes: [
    [
      "path",
      {
        "d": "M12.6 5.4L12.6 18.6A0.6 0.6 0 0 1 11.4 18.6L11.4 5.4A0.6 0.6 0 0 1 12.6 5.4zM9.6 11.4L5.048 11.4L6.424 10.024A0.6 0.6 0 0 0 5.575 9.175L3.175 11.576A0.6 0.6 0 0 0 3.175 12.424L5.575 14.824A0.6 0.6 0 0 0 6.424 13.976L5.048 12.6L9.6 12.6A0.6 0.6 0 0 0 9.6 11.4zM20.825 11.576L18.425 9.175A0.6 0.6 0 0 0 17.576 10.024L18.952 11.4L14.4 11.4A0.6 0.6 0 0 0 14.4 12.6L18.952 12.6L17.576 13.976A0.6 0.6 0 0 0 18.425 14.824L20.825 12.424A0.6 0.6 0 0 0 20.825 11.576z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "SpaceBetweenVertical": {
    // phosphor/arrows-out-line-vertical (×0.8) — inks 14.4x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M19.2 12A0.6 0.6 0 0 1 18.6 12.6L5.4 12.6A0.6 0.6 0 0 1 5.4 11.4L18.6 11.4A0.6 0.6 0 0 1 19.2 12zM10.024 6.424L11.4 5.048L11.4 9.6A0.6 0.6 0 0 0 12.6 9.6L12.6 5.048L13.976 6.424A0.6 0.6 0 0 0 14.824 5.575L12.424 3.175A0.6 0.6 0 0 0 11.576 3.175L9.175 5.575A0.6 0.6 0 0 0 10.024 6.424zM13.976 17.576L12.6 18.952L12.6 14.4A0.6 0.6 0 0 0 11.4 14.4L11.4 18.952L10.024 17.576A0.6 0.6 0 0 0 9.175 18.425L11.576 20.825A0.6 0.6 0 0 0 12.424 20.825L14.824 18.425A0.6 0.6 0 0 0 13.976 17.576z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "Sparkles": {
    // phosphor/sparkle — inks 21.8x21.8 of 24
    shapes: [
    [
      "path",
      {
        "d": "M18.523 12.099L13.688 10.313L11.906 5.473A1.492 1.492 0 0 0 9.105 5.473L7.313 10.313L2.473 12.094A1.492 1.492 0 0 0 2.473 14.895L7.313 16.688L9.094 21.527A1.492 1.492 0 0 0 11.895 21.527L13.688 16.688L18.527 14.906A1.492 1.492 0 0 0 18.527 12.105zM12.844 15.396A0.75 0.75 0 0 0 12.399 15.84L10.5 20.986L8.604 15.844A0.75 0.75 0 0 0 8.156 15.396L3.014 13.5L8.156 11.604A0.75 0.75 0 0 0 8.604 11.156L10.5 6.014L12.396 11.156A0.75 0.75 0 0 0 12.84 11.601L17.986 13.5zM13.5 3.75A0.75 0.75 0 0 1 14.25 3L15.75 3L15.75 1.5A0.75 0.75 0 0 1 17.25 1.5L17.25 3L18.75 3A0.75 0.75 0 0 1 18.75 4.5L17.25 4.5L17.25 6A0.75 0.75 0 0 1 15.75 6L15.75 4.5L14.25 4.5A0.75 0.75 0 0 1 13.5 3.75zM23.25 8.25A0.75 0.75 0 0 1 22.5 9L21.75 9L21.75 9.75A0.75 0.75 0 0 1 20.25 9.75L20.25 9L19.5 9A0.75 0.75 0 0 1 19.5 7.5L20.25 7.5L20.25 6.75A0.75 0.75 0 0 1 21.75 6.75L21.75 7.5L22.5 7.5A0.75 0.75 0 0 1 23.25 8.25z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "Square": {
    // phosphor/square — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M19.5 3L4.5 3A1.5 1.5 0 0 0 3 4.5L3 19.5A1.5 1.5 0 0 0 4.5 21L19.5 21A1.5 1.5 0 0 0 21 19.5L21 4.5A1.5 1.5 0 0 0 19.5 3zM19.5 19.5L4.5 19.5L4.5 4.5L19.5 4.5L19.5 19.5z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "Sun": {
    // kept: lucide/Sun — inks 18.0x18.0 of 24
    stroke: 2,
    shapes: [
    [
      "circle",
      {
        "cx": 12,
        "cy": 12,
        "r": 3.6,
      },
    ],
    [
      "path",
      {
        "d": "M12 3L12 4.8",
      },
    ],
    [
      "path",
      {
        "d": "M12 19.2L12 21",
      },
    ],
    [
      "path",
      {
        "d": "M5.637 5.637L6.906 6.906",
      },
    ],
    [
      "path",
      {
        "d": "M17.094 17.094L18.363 18.363",
      },
    ],
    [
      "path",
      {
        "d": "M3 12L4.8 12",
      },
    ],
    [
      "path",
      {
        "d": "M19.2 12L21 12",
      },
    ],
    [
      "path",
      {
        "d": "M6.906 17.094L5.637 18.363",
      },
    ],
    [
      "path",
      {
        "d": "M18.363 5.637L17.094 6.906",
      },
    ],
    ],
  },
  "TextAlignBottom": {
    // phosphor/arrow-line-down — inks 18.0x18.8 of 24
    shapes: [
    [
      "path",
      {
        "d": "M4.719 11.031A0.75 0.75 0 0 1 5.781 9.969L11.25 15.44L11.25 3A0.75 0.75 0 0 1 12.75 3L12.75 15.44L18.219 9.969A0.75 0.75 0 0 1 19.281 11.031L12.531 17.781A0.75 0.75 0 0 1 11.469 17.781zM20.25 19.5L3.75 19.5A0.75 0.75 0 0 0 3.75 21L20.25 21A0.75 0.75 0 0 0 20.25 19.5z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "TextAlignCenter": {
    // phosphor/text-align-center — inks 18.0x12.8 of 24
    shapes: [
    [
      "path",
      {
        "d": "M3 6A0.75 0.75 0 0 1 3.75 5.25L20.25 5.25A0.75 0.75 0 0 1 20.25 6.75L3.75 6.75A0.75 0.75 0 0 1 3 6zM6 9A0.75 0.75 0 0 0 6 10.5L18 10.5A0.75 0.75 0 0 0 18 9zM20.25 12.75L3.75 12.75A0.75 0.75 0 0 0 3.75 14.25L20.25 14.25A0.75 0.75 0 0 0 20.25 12.75zM18 16.5L6 16.5A0.75 0.75 0 0 0 6 18L18 18A0.75 0.75 0 0 0 18 16.5z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "TextAlignJustify": {
    // phosphor/text-align-justify — inks 18.0x12.8 of 24
    shapes: [
    [
      "path",
      {
        "d": "M3 6A0.75 0.75 0 0 1 3.75 5.25L20.25 5.25A0.75 0.75 0 0 1 20.25 6.75L3.75 6.75A0.75 0.75 0 0 1 3 6zM20.25 9L3.75 9A0.75 0.75 0 0 0 3.75 10.5L20.25 10.5A0.75 0.75 0 0 0 20.25 9zM20.25 12.75L3.75 12.75A0.75 0.75 0 0 0 3.75 14.25L20.25 14.25A0.75 0.75 0 0 0 20.25 12.75zM20.25 16.5L3.75 16.5A0.75 0.75 0 0 0 3.75 18L20.25 18A0.75 0.75 0 0 0 20.25 16.5z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "TextAlignLeft": {
    // phosphor/text-align-left — inks 18.0x12.8 of 24
    shapes: [
    [
      "path",
      {
        "d": "M3 6A0.75 0.75 0 0 1 3.75 5.25L20.25 5.25A0.75 0.75 0 0 1 20.25 6.75L3.75 6.75A0.75 0.75 0 0 1 3 6zM3.75 10.5L15.75 10.5A0.75 0.75 0 0 0 15.75 9L3.75 9A0.75 0.75 0 0 0 3.75 10.5zM20.25 12.75L3.75 12.75A0.75 0.75 0 0 0 3.75 14.25L20.25 14.25A0.75 0.75 0 0 0 20.25 12.75zM15.75 16.5L3.75 16.5A0.75 0.75 0 0 0 3.75 18L15.75 18A0.75 0.75 0 0 0 15.75 16.5z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "TextAlignMiddle": {
    // phosphor/arrows-in-line-vertical (×0.8) — inks 14.4x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M19.2 12A0.6 0.6 0 0 1 18.6 12.6L5.4 12.6A0.6 0.6 0 0 1 5.4 11.4L18.6 11.4A0.6 0.6 0 0 1 19.2 12zM11.576 10.024A0.6 0.6 0 0 0 12.424 10.024L14.824 7.625A0.6 0.6 0 0 0 13.976 6.775L12.6 8.152L12.6 3.6A0.6 0.6 0 0 0 11.4 3.6L11.4 8.152L10.024 6.775A0.6 0.6 0 0 0 9.175 7.625zM12.424 13.976A0.6 0.6 0 0 0 11.576 13.976L9.175 16.375A0.6 0.6 0 0 0 10.024 17.224L11.4 15.848L11.4 20.4A0.6 0.6 0 0 0 12.6 20.4L12.6 15.848L13.976 17.224A0.6 0.6 0 0 0 14.824 16.375z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "TextAlignRight": {
    // phosphor/text-align-right — inks 18.0x12.8 of 24
    shapes: [
    [
      "path",
      {
        "d": "M3 6A0.75 0.75 0 0 1 3.75 5.25L20.25 5.25A0.75 0.75 0 0 1 20.25 6.75L3.75 6.75A0.75 0.75 0 0 1 3 6zM20.25 9L8.25 9A0.75 0.75 0 0 0 8.25 10.5L20.25 10.5A0.75 0.75 0 0 0 20.25 9zM20.25 12.75L3.75 12.75A0.75 0.75 0 0 0 3.75 14.25L20.25 14.25A0.75 0.75 0 0 0 20.25 12.75zM20.25 16.5L8.25 16.5A0.75 0.75 0 0 0 8.25 18L20.25 18A0.75 0.75 0 0 0 20.25 16.5z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "TextAlignTop": {
    // phosphor/arrow-line-up — inks 18.0x18.8 of 24
    shapes: [
    [
      "path",
      {
        "d": "M19.281 12.969A0.75 0.75 0 0 1 18.219 14.031L12.75 8.56L12.75 21A0.75 0.75 0 0 1 11.25 21L11.25 8.56L5.781 14.031A0.75 0.75 0 0 1 4.719 12.969L11.469 6.219A0.75 0.75 0 0 1 12.531 6.219zM20.25 3L3.75 3A0.75 0.75 0 0 0 3.75 4.5L20.25 4.5A0.75 0.75 0 0 0 20.25 3z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "ToolClose": {
    // kept: native — inks 15.1x15.1 of 24
    stroke: 2,
    shapes: [
    [
      "path",
      {
        "d": "M4.800000000000001 4.800000000000001A1.1249999999999998 1.1249999999999998 0 0 0 4.800000000000001 6.390990257669731L17.609009742330265 19.200000000000003A1.125 1.125 0 0 0 19.200000000000003 19.200000000000003L19.200000000000003 19.200000000000003A1.125 1.125 0 0 0 19.200000000000003 17.609009742330265L6.390990257669731 4.800000000000001A1.1249999999999998 1.1249999999999998 0 0 0 4.800000000000001 4.800000000000001L4.800000000000001 4.800000000000001z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M4.800000000000001 19.200000000000003A1.1249999999999996 1.1249999999999996 0 0 0 6.390990257669731 19.200000000000003L19.200000000000003 6.390990257669731A1.1249999999999996 1.1249999999999996 0 0 0 19.200000000000003 4.800000000000001L19.200000000000003 4.799999999999999A1.125 1.125 0 0 0 17.60900974233027 4.800000000000001L4.800000000000001 17.60900974233027A1.125 1.125 0 0 0 4.799999999999999 19.200000000000003L4.800000000000001 19.200000000000003z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ToolRedo": {
    // kept: native — inks 17.3x18.0 of 24
    stroke: 2,
    shapes: [
    [
      "path",
      {
        "d": "M16.125 3L20.25 7.125L16.125 11.25L12.943019484660537 11.25L17.06801948466054 7.125L12.943019484660537 3z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 6,
        "width": 9,
        "height": 2.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M10.5 21A7.5 7.5 0 0 1 10.5 6L10.5 8.25A5.25 5.25 0 0 0 10.5 18.75z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 18.75,
        "width": 4.5,
        "height": 2.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ToolUndo": {
    // kept: native — inks 17.3x18.0 of 24
    stroke: 2,
    shapes: [
    [
      "path",
      {
        "d": "M7.875 3L3.75 7.125L7.875 11.25L11.056980515339465 11.25L6.931980515339465 7.125L11.056980515339465 3z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 4.5,
        "y": 6,
        "width": 9,
        "height": 2.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M13.5 6A7.5 7.5 0 0 1 13.5 21L13.5 18.75A5.25 5.25 0 0 0 13.5 8.25z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 9,
        "y": 18.75,
        "width": 4.5,
        "height": 2.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Trash": {
    // kept: foundations/trash-2, fitted ×0.909 — inks 16.6x18.2 of 24
    stroke: 2,
    shapes: [
    [
      "path",
      {
        "d": "M3.7054 5.3884L20.2946 5.3884",
      },
    ],
    [
      "path",
      {
        "d": "M9.1073 5.3882L9.1073 3.9427A1.0327 1.0327 0 0 1 10.14 2.9091L13.86 2.9091A1.0327 1.0327 0 0 1 14.8927 3.9418L14.8927 5.3882",
      },
    ],
    [
      "path",
      {
        "d": "M5.07 5.3882L6.8764 19.8245A1.4455 1.4455 0 0 0 8.3109 21.0909L15.6891 21.0909A1.4455 1.4455 0 0 0 17.1236 19.8245L18.93 5.3882",
      },
    ],
    ],
  },
  "Type": {
    // phosphor/text-t (×1.15) — inks 17.3x17.3 of 24
    shapes: [
    [
      "path",
      {
        "d": "M20.625 4.238L20.625 7.688A0.862 0.862 0 0 1 18.9 7.688L18.9 5.1L12.862 5.1L12.862 18.9L15.45 18.9A0.862 0.862 0 0 1 15.45 20.625L8.55 20.625A0.862 0.862 0 0 1 8.55 18.9L11.137 18.9L11.137 5.1L5.1 5.1L5.1 7.688A0.862 0.862 0 0 1 3.375 7.688L3.375 4.238A0.862 0.862 0 0 1 4.238 3.375L19.763 3.375A0.862 0.862 0 0 1 20.625 4.238z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "WrapText": {
    // phosphor/arrow-u-down-left — inks 19.5x16.5 of 24
    shapes: [
    [
      "path",
      {
        "d": "M21.75 10.5A6.007 6.007 0 0 1 15.75 16.5L4.81 16.5L8.031 19.719A0.75 0.75 0 0 1 6.969 20.781L2.469 16.281A0.75 0.75 0 0 1 2.469 15.219L6.969 10.719A0.75 0.75 0 0 1 8.031 11.781L4.81 15L15.75 15A4.5 4.5 0 0 0 15.75 6L7.5 6A0.75 0.75 0 0 1 7.5 4.5L15.75 4.5A6.007 6.007 0 0 1 21.75 10.5z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "X": {
    // phosphor/x — inks 15.0x15.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M19.281 18.219A0.75 0.75 0 0 1 18.219 19.281L12 13.06L5.781 19.281A0.75 0.75 0 0 1 4.719 18.219L10.94 12L4.719 5.781A0.75 0.75 0 0 1 5.781 4.719L12 10.94L18.219 4.719A0.75 0.75 0 0 1 19.281 5.781L13.06 12z",
        "fill": "currentColor",
      },
    ],
    ],
  },
  "XSmall": {
    // phosphor/x (×0.85) — inks 12.8x12.8 of 24
    shapes: [
    [
      "path",
      {
        "d": "M18.189 17.286A0.637 0.637 0 0 1 17.286 18.189L12 12.901L6.714 18.189A0.637 0.637 0 0 1 5.811 17.286L11.099 12L5.811 6.714A0.637 0.637 0 0 1 6.714 5.811L12 11.099L17.286 5.811A0.637 0.637 0 0 1 18.189 6.714L12.901 12z",
        "fill": "currentColor",
      },
    ],
    ],
  },
} as const satisfies Record<string, IconData>

export type IconName = keyof typeof ICONS

export const ICON_NAMES = Object.keys(ICONS) as IconName[]

/** The glyphs that keep their pre-Phosphor drawing. */
export const LEGACY_ICON_NAMES = ["AlignCenterHorizontal","AlignCenterVertical","AlignEndHorizontal","AlignEndVertical","AlignStartHorizontal","AlignStartVertical","ExternalLink","Grid2x2","MessageSquare","Moon","PanelLeft","PanelRight","Sun","ToolClose","ToolRedo","ToolUndo","Trash"] as const satisfies readonly IconName[]

/**
 * The kept glyphs authored on the native 16 lattice. They land on whole device
 * pixels only at a multiple of 8, so they may be drawn at `icon.action` (16)
 * or `icon.feature` (24) and nowhere else; `test/icon-cases.mjs` greps the
 * source for a call that breaks this.
 */
export const NATIVE_ICON_NAMES = ["AlignCenterHorizontal","AlignCenterVertical","AlignEndHorizontal","AlignEndVertical","AlignStartHorizontal","AlignStartVertical","PanelLeft","PanelRight","ToolClose","ToolRedo","ToolUndo"] as const satisfies readonly IconName[]

export const NATIVE_ICON_SIZES = [16,24] as const satisfies readonly IconSize[]

const SVG_NS = "http://www.w3.org/2000/svg"

function build(node: IconNode): SVGElement {
  const [tag, attrs, children] = node
  const element = document.createElementNS(SVG_NS, tag)
  for (const [key, value] of Object.entries(attrs)) element.setAttribute(key, String(value))
  for (const child of children ?? []) element.append(build(child))
  return element
}

/**
 * Draw one glyph from its data.
 *
 * Exported so the host's own icon set — served by the loopback `/icons` route
 * and offered as variants in the inspector — is drawn by the same rules as
 * these. Two renderers would be two answers to "how big is a glyph", and only
 * one of them would be right.
 */
export function drawIcon(data: IconData, size: IconSize = 16, weight: IconWeight = "auto"): SVGSVGElement {
  const svg = document.createElementNS(SVG_NS, "svg")
  svg.setAttribute("width", String(size))
  svg.setAttribute("height", String(size))
  svg.setAttribute("viewBox", "0 0 24 24")
  // The root fill is opt-in and the outline is what `auto` means. Every shape
  // states its own fill, so this reaches only a drawing that does not.
  svg.setAttribute("fill", weight === "filled" ? "currentColor" : "none")
  svg.setAttribute("stroke", "currentColor")
  const stroke = data.stroke ?? STROKE_FOR_SIZE[size]
  svg.setAttribute("stroke-width", String(stroke))
  svg.style.setProperty(ICON_STROKE_VARIABLE, String(stroke))
  svg.setAttribute("stroke-linecap", "round")
  svg.setAttribute("stroke-linejoin", "round")
  svg.setAttribute(ICON_MARKER_ATTRIBUTE, "")
  svg.setAttribute("aria-hidden", "true")
  // The fill weight when the glyph has one, its own shapes otherwise.
  const shapes = weight === "filled" && data.filled ? data.filled : data.shapes
  for (const node of shapes) svg.append(build(node))
  return svg
}

/**
 * One glyph, sized and decorative.
 *
 * Colour comes from `currentColor`, never a token: the same mark is drawn on a
 * rest row, a hovered row and a filled selected row, and only the caller knows
 * which.
 */
export function icon(name: IconName, size: IconSize = 16, weight: IconWeight = "auto"): SVGSVGElement {
  const svg = drawIcon(ICONS[name], size, weight)
  /*
   * The marker carries the NAME, so a stylesheet can say something about one
   * mark — the optical correction for `Cursor` in `css/icons.ts`. Set here
   * and not in `drawIcon`, because `drawIcon` also renders the HOST app's own
   * icons, whose names belong to a set this package did not author.
   */
  svg.setAttribute(ICON_MARKER_ATTRIBUTE, name)
  return svg
}

/**
 * A glyph from the HOST's own icon set, which is a different set of rules.
 *
 * The app being edited ships its own icons, served by the loopback `/icons`
 * route so the inspector can offer one in place of another. Those are drawn the
 * way their author drew them: one weight, whatever grid and stroke they use,
 * nothing normalised. This editor does not get to re-window a glyph it is about
 * to write into someone else's source.
 */
export interface HostIconData {
  nodes: IconNode[]
  rootFill: string
  rootStroke?: string
}

export function drawHostIcon(data: HostIconData, size: IconSize = 16): SVGSVGElement {
  const svg = document.createElementNS(SVG_NS, "svg")
  svg.setAttribute("width", String(size))
  svg.setAttribute("height", String(size))
  svg.setAttribute("viewBox", "0 0 24 24")
  svg.setAttribute("fill", data.rootFill === "none" ? "none" : "currentColor")
  if (data.rootStroke) {
    svg.setAttribute("stroke", "currentColor")
    svg.setAttribute("stroke-width", "2")
    svg.setAttribute("stroke-linecap", "round")
    svg.setAttribute("stroke-linejoin", "round")
  }
  svg.setAttribute("aria-hidden", "true")
  for (const node of data.nodes) svg.append(build(node))
  return svg
}
